### ISSUE TITLE
Switch to well known large communities for RPKI

### ISSUE THREAD

**Issue by Cybertinus** [coloclue/kees#18]
We are using our own defined large communities for the different RPKI states (valid, invalid, unknown). There are well known large communities for the different RPKI states. To adhere to standards like this, we should update our configurations to start using those.
The well known large communities are:
* valid 0x4300:0
* unkown 0x4300:1
* invalid 0x4300:2

**Comment by job** [comment]
these are not "well known large communities", but "incorrectly formatted non-transitive extended communities". This is a bug that came from Juniper documentation that is now being fixed.

You'll want to use:

valid 0x4300:0.0.0.0:0
unkown 0x4300:0.0.0.0:1
invalid 0x4300:0.0.0.0:2

**Comment by job** [comment]
See https://tools.ietf.org/html/rfc8097 for the standard

**Comment by Cybertinus** [comment]
You are absolutely right Job. Thanks for pointing this out. And at the moment we have these extended communities implemented (https://github.com/coloclue/kees/blob/9093e8494e563a0cd9be402341b1f4f7062294bf/templates/afi_specific_filters.j2#L99 they are defined in this function)

So, I'm closing this issue, as it has been resolved
